apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-xfce-vnc
  labels:
    app: ubuntu-xfce-vnc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-xfce-vnc
  template:
    metadata:
      labels:
        app: ubuntu-xfce-vnc
    spec:
      containers:
      - name: ubuntu-xfce-vnc
        image: <your registry>
        ports:
        - containerPort: 5900
          name: vnc
        - containerPort: 6081
          name: novnc
